Resources:
  NotificationDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: '${self:service}-${self:provider.stage}-Notification'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: targetId
          AttributeType: S
        - AttributeName: createAt
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: targetId
          KeyType: HASH
        - AttributeName: createAt
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: targetIdLocalIndex
          KeySchema:
            - AttributeName: targetId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: userIdGlobalIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
